### PR TITLE
SLING-8309: Allow adding CommitHooks and EditorProviders dynamically from bundles

### PR DESCRIPTION
**Pull request by sdumitriu**

### CODE REVIEW

**Comment by rombert** [comment]
A SonarQube report for the changes added _only by this pull request_ was generated. Please review it at https://builds.apache.org/job/Sling/job/sling-org-apache-sling-jcr-oak-server/job/PR-2/1/artifact/target/sonar/issues-report/issues-report-light.html

**Comment by rombert** [comment]
A SonarQube report for the changes added _only by this pull request_ was generated. Please review it at https://builds.apache.org/job/Sling/job/sling-org-apache-sling-jcr-oak-server/job/PR-2/2/artifact/target/sonar/issues-report/issues-report-light.html

**Comment by rombert** [comment]
@sdumitriu - please disregard code coverage errors, we have a known issue with that

**Comment by oliverlietz** [comment]
https://issues.apache.org/jira/browse/SLING-8309 – Won't Fix.

**Pull request closed without merging**
